
-- RESTAURANT MANAGER - MANUAL USER LOGIN SETUP
-- Run this full file once in Supabase SQL Editor.
-- Default login created:
-- Username: admin
-- Password: admin123
--
-- IMPORTANT:
-- This version uses an app-level manual login system, not Supabase Auth.
-- Change the default admin password after first login.

create extension if not exists pgcrypto;

-- =========================
-- 1. MANUAL APP USERS
-- =========================

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  display_name text,
  password_hash text not null,
  role text not null default 'staff' check (role in ('admin','manager','staff','inventory_user')),
  active boolean not null default true,
  created_at timestamp with time zone default now()
);

insert into public.app_users (username, display_name, password_hash, role, active)
values ('admin', 'Main Admin', crypt('admin123', gen_salt('bf')), 'admin', true)
on conflict (username) do nothing;

-- =========================
-- 2. ROLE PERMISSIONS
-- =========================

create table if not exists public.role_permissions (
  id bigint generated by default as identity primary key,
  role text not null unique check (role in ('admin','manager','staff','inventory_user')),

  can_view_dashboard boolean not null default false,

  can_view_sales boolean not null default false,
  can_add_sales boolean not null default false,
  can_edit_sales boolean not null default false,
  can_delete_sales boolean not null default false,

  can_view_expenses boolean not null default false,
  can_add_expenses boolean not null default false,
  can_edit_expenses boolean not null default false,
  can_delete_expenses boolean not null default false,

  can_view_inventory boolean not null default false,
  can_add_inventory boolean not null default false,
  can_edit_inventory boolean not null default false,
  can_delete_inventory boolean not null default false,

  can_view_sop boolean not null default false,
  can_add_sop boolean not null default false,
  can_edit_sop boolean not null default false,
  can_delete_sop boolean not null default false,

  can_view_reports boolean not null default false,
  can_manage_settings boolean not null default false,

  updated_at timestamp with time zone default now()
);

insert into public.role_permissions (
  role,
  can_view_dashboard,
  can_view_sales, can_add_sales, can_edit_sales, can_delete_sales,
  can_view_expenses, can_add_expenses, can_edit_expenses, can_delete_expenses,
  can_view_inventory, can_add_inventory, can_edit_inventory, can_delete_inventory,
  can_view_sop, can_add_sop, can_edit_sop, can_delete_sop,
  can_view_reports,
  can_manage_settings
)
values
('admin',
 true,
 true,true,true,true,
 true,true,true,true,
 true,true,true,true,
 true,true,true,true,
 true,
 true),
('manager',
 true,
 true,true,true,false,
 true,true,true,false,
 true,true,true,false,
 true,true,true,false,
 true,
 false),
('staff',
 false,
 true,true,false,false,
 true,true,false,false,
 false,false,false,false,
 false,false,false,false,
 false,
 false),
('inventory_user',
 false,
 false,false,false,false,
 true,true,false,false,
 true,true,true,false,
 true,false,false,false,
 false,
 false)
on conflict (role) do nothing;

-- =========================
-- 3. CORE BUSINESS TABLES
-- =========================

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null unique,
  default_selling_price numeric not null default 0,
  default_plate_cost numeric not null default 0,
  active boolean not null default true,
  created_at timestamp with time zone default now()
);

insert into public.menu_items (name, default_selling_price, default_plate_cost)
values
('Chicken Biryani',120,0),
('Veg Biryani',100,0),
('Veg Thali',120,0),
('Bangda Thali',150,0),
('Fish Thali',150,0),
('Prawns Thali',180,0),
('King Fish Thali',220,0),
('Ros Omelette',80,0),
('Tea',20,0),
('Cold Drink',40,0)
on conflict (name) do nothing;

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  username text,
  sale_date date not null default current_date,
  item_name text not null,
  quantity numeric not null default 0,
  selling_price numeric not null default 0,
  total_amount numeric generated always as (quantity * selling_price) stored,
  payment_mode text not null default 'UPI',
  notes text,
  plate_cost numeric default 0,
  total_food_cost numeric default 0,
  gross_profit numeric default 0,
  created_at timestamp with time zone default now()
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  username text,
  expense_date date not null default current_date,
  category text not null default 'Raw Material',
  item_name text not null,
  quantity numeric,
  unit text,
  total_price numeric not null default 0,
  buying_price numeric,
  supplier text,
  price_per_unit numeric generated always as (
    case when quantity is not null and quantity > 0 then total_price / quantity else null end
  ) stored,
  inventory_updated boolean default false,
  notes text,
  created_at timestamp with time zone default now()
);

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  raw_material_name text not null,
  category text default 'Raw Material',
  unit text not null default 'pieces',
  opening_stock numeric not null default 0,
  stock_added numeric not null default 0,
  stock_used numeric not null default 0,
  closing_stock numeric generated always as (opening_stock + stock_added - stock_used) stored,
  minimum_stock_level numeric not null default 0,
  purchase_price numeric,
  last_purchase_price numeric default 0,
  average_purchase_price numeric default 0,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists public.sop_recipes (
  id bigint generated by default as identity primary key,
  menu_item_name text not null,
  selling_price numeric not null default 0,
  quantity_prepared numeric not null default 0,
  plates_produced numeric not null default 0,
  total_recipe_cost numeric not null default 0,
  cost_per_plate numeric not null default 0,
  profit_per_plate numeric not null default 0,
  preparation_steps text,
  hygiene_instructions text,
  portion_size text,
  plating_instructions text,
  storage_instructions text,
  created_at timestamp with time zone default now()
);

create table if not exists public.sop_ingredients (
  id bigint generated by default as identity primary key,
  recipe_id bigint references public.sop_recipes(id) on delete cascade,
  ingredient_name text not null,
  quantity_required numeric not null default 0,
  unit text not null,
  ingredient_price numeric not null default 0,
  total_cost numeric generated always as (quantity_required * ingredient_price) stored,
  created_at timestamp with time zone default now()
);

create table if not exists public.recipe_preparations (
  id bigint generated by default as identity primary key,
  recipe_id bigint references public.sop_recipes(id) on delete set null,
  preparation_date date not null default current_date,
  menu_item_name text not null,
  plates_prepared numeric not null default 0,
  total_cost numeric not null default 0,
  cost_per_plate numeric not null default 0,
  created_at timestamp with time zone default now()
);

create table if not exists public.inventory_transactions (
  id bigint generated by default as identity primary key,
  item_name text not null,
  category text default 'Raw Material',
  unit text,
  transaction_type text not null check (transaction_type in ('purchase','recipe_use','adjustment')),
  quantity numeric not null default 0,
  amount numeric default 0,
  reference_table text,
  reference_id bigint,
  transaction_date date not null default current_date,
  created_at timestamp with time zone default now()
);

-- If these columns are missing from old tables, add them safely.

alter table public.sales add column if not exists username text;
alter table public.sales add column if not exists notes text;
alter table public.sales add column if not exists plate_cost numeric default 0;
alter table public.sales add column if not exists total_food_cost numeric default 0;
alter table public.sales add column if not exists gross_profit numeric default 0;

alter table public.expenses add column if not exists username text;
alter table public.expenses add column if not exists unit text;
alter table public.expenses add column if not exists buying_price numeric;
alter table public.expenses add column if not exists inventory_updated boolean default false;

alter table public.inventory add column if not exists category text default 'Raw Material';
alter table public.inventory add column if not exists last_purchase_price numeric default 0;
alter table public.inventory add column if not exists average_purchase_price numeric default 0;
alter table public.inventory add column if not exists updated_at timestamp with time zone default now();

-- =========================
-- 4. LOGIN + USER FUNCTIONS
-- =========================

create or replace function public.app_login(p_username text, p_password text)
returns table (
  id bigint,
  username text,
  display_name text,
  role text,
  active boolean
)
language sql
security definer
set search_path = public
as $$
  select u.id, u.username, u.display_name, u.role, u.active
  from public.app_users u
  where lower(u.username) = lower(p_username)
    and u.password_hash = crypt(p_password, u.password_hash)
    and u.active = true
  limit 1;
$$;

create or replace function public.app_create_user(
  p_username text,
  p_password text,
  p_display_name text,
  p_role text
)
returns public.app_users
language plpgsql
security definer
set search_path = public
as $$
declare
  new_user public.app_users;
begin
  if p_role not in ('admin','manager','staff','inventory_user') then
    raise exception 'Invalid role';
  end if;

  insert into public.app_users (username, display_name, password_hash, role, active)
  values (lower(trim(p_username)), p_display_name, crypt(p_password, gen_salt('bf')), p_role, true)
  returning * into new_user;

  return new_user;
end;
$$;

create or replace function public.app_update_user(
  p_id bigint,
  p_display_name text,
  p_role text,
  p_active boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_role not in ('admin','manager','staff','inventory_user') then
    raise exception 'Invalid role';
  end if;

  update public.app_users
  set display_name = p_display_name,
      role = p_role,
      active = p_active
  where id = p_id;
end;
$$;

create or replace function public.app_change_password(
  p_id bigint,
  p_new_password text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.app_users
  set password_hash = crypt(p_new_password, gen_salt('bf'))
  where id = p_id;
end;
$$;

-- =========================
-- 5. INVENTORY AUTO UPDATE
-- =========================

create or replace function public.update_inventory_from_expense()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  existing_inventory_id bigint;
  current_added numeric := 0;
  current_avg numeric := 0;
  current_qty numeric := 0;
  new_rate numeric := 0;
  calculated_avg numeric := 0;
begin
  if new.quantity is null or new.quantity <= 0 then
    return new;
  end if;

  new_rate := coalesce(new.total_price, new.buying_price, 0) / new.quantity;

  select id, stock_added, average_purchase_price
  into existing_inventory_id, current_added, current_avg
  from public.inventory
  where lower(raw_material_name) = lower(new.item_name)
  order by id desc
  limit 1;

  if existing_inventory_id is not null then
    current_qty := coalesce(current_added, 0);

    calculated_avg := case
      when (current_qty + new.quantity) > 0
      then ((current_qty * coalesce(current_avg, 0)) + (new.quantity * new_rate)) / (current_qty + new.quantity)
      else new_rate
    end;

    update public.inventory
    set stock_added = coalesce(stock_added, 0) + new.quantity,
        category = coalesce(new.category, category),
        unit = coalesce(new.unit, unit),
        last_purchase_price = new_rate,
        average_purchase_price = calculated_avg,
        purchase_price = coalesce(new.total_price, new.buying_price, purchase_price),
        updated_at = now()
    where id = existing_inventory_id;
  else
    insert into public.inventory (
      raw_material_name,
      category,
      unit,
      opening_stock,
      stock_added,
      stock_used,
      minimum_stock_level,
      purchase_price,
      last_purchase_price,
      average_purchase_price
    )
    values (
      new.item_name,
      coalesce(new.category, 'Raw Material'),
      coalesce(new.unit, 'pieces'),
      0,
      new.quantity,
      0,
      0,
      coalesce(new.total_price, new.buying_price, 0),
      new_rate,
      new_rate
    );
  end if;

  insert into public.inventory_transactions (
    item_name, category, unit, transaction_type, quantity, amount,
    reference_table, reference_id, transaction_date
  )
  values (
    new.item_name, coalesce(new.category, 'Raw Material'), new.unit, 'purchase',
    new.quantity, coalesce(new.total_price, new.buying_price, 0),
    'expenses', new.id, new.expense_date
  );

  new.inventory_updated := true;
  return new;
end;
$$;

drop trigger if exists trg_update_inventory_from_expense on public.expenses;

create trigger trg_update_inventory_from_expense
before insert on public.expenses
for each row
execute function public.update_inventory_from_expense();

-- =========================
-- 6. RLS + POLICIES
-- =========================
-- Since this app uses manual app-level login instead of Supabase Auth,
-- these policies allow the GitHub Pages frontend to read/write with the anon key.
-- Keep your GitHub repository private if you do not want your Supabase project visible.

alter table public.app_users enable row level security;
alter table public.role_permissions enable row level security;
alter table public.menu_items enable row level security;
alter table public.sales enable row level security;
alter table public.expenses enable row level security;
alter table public.inventory enable row level security;
alter table public.sop_recipes enable row level security;
alter table public.sop_ingredients enable row level security;
alter table public.recipe_preparations enable row level security;
alter table public.inventory_transactions enable row level security;

do $$
declare
  t text;
begin
  foreach t in array array[
    'app_users',
    'role_permissions',
    'menu_items',
    'sales',
    'expenses',
    'inventory',
    'sop_recipes',
    'sop_ingredients',
    'recipe_preparations',
    'inventory_transactions'
  ]
  loop
    if not exists (
      select 1 from pg_policies
      where schemaname = 'public'
      and tablename = t
      and policyname = 'app anon select'
    ) then
      execute format('create policy "app anon select" on public.%I for select to anon using (true)', t);
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'public'
      and tablename = t
      and policyname = 'app anon insert'
    ) then
      execute format('create policy "app anon insert" on public.%I for insert to anon with check (true)', t);
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'public'
      and tablename = t
      and policyname = 'app anon update'
    ) then
      execute format('create policy "app anon update" on public.%I for update to anon using (true) with check (true)', t);
    end if;

    if not exists (
      select 1 from pg_policies
      where schemaname = 'public'
      and tablename = t
      and policyname = 'app anon delete'
    ) then
      execute format('create policy "app anon delete" on public.%I for delete to anon using (true)', t);
    end if;
  end loop;
end $$;
